# ML Zoomcamp Cohort 2024
# Homework 1

### Imports


In [1]:
import numpy as np
import pandas as pd

### Q1. Pandas version
What's the version of Pandas that you installed?

In [2]:
print(f"Installed pandas version is: {pd.__version__}")

Installed pandas version is: 2.2.3


In [3]:
laptops_df = pd.read_csv("../data/laptops.csv")
laptops_df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

### Q2. Records count
How many records are in the dataset?

In [4]:
print(f"There are {laptops_df.shape[0]} records in the dataset")

There are 2160 records in the dataset


### Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [5]:
print(f"There are {laptops_df['Brand'].nunique()} different laptop brands in the dataset")

There are 27 different laptop brands in the dataset


### Q4. Missing values
How many columns in the dataset have missing values?

In [6]:
print(f"Number of columns with missing values: {laptops_df.isnull().any().sum()}")

Number of columns with missing values: 3


### Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [7]:
print(f"The maximum price of Dell notebooks is: {laptops_df[laptops_df['Brand']=='Dell']['Final Price'].max()}")

The maximum price of Dell notebooks is: 3936.0


In [8]:
laptops_df[laptops_df['Brand']=='Dell']['Model'].unique()

array(['Vostro', 'Latitude', 'XPS', 'Precision'], dtype=object)

### Q6. Median value of Screen
1. Find the median value of Screen column in the dataset.
2. Next, calculate the most frequent value of the same Screen column.
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
4. Now, calculate the median value of Screen once again.

1.

In [9]:
init_median = laptops_df['Screen'].median()
print(f"The initial median in the dataset is: {init_median}")

The initial median in the dataset is: 15.6


2.

In [17]:
mode = laptops_df['Screen'].mode()
print(f"The most frequent value of the feature 'Screen' is : {mode[0]}")

The most frequent value of the feature 'Screen' is : 15.6


3.

In [11]:
laptops_df['Screen'] = laptops_df['Screen'].fillna(mode)

4.

In [12]:
final_median = laptops_df['Screen'].median()
print(f"The median after 'fillna' is: {final_median}")

The median after 'fillna' is: 15.6


### Q7. Sum of weights

1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns `RAM`, `Storage`, `Screen`.
3. Get the underlying NumPy array. Let's call it `X`.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
5. Compute the inverse of `XTX`.
6. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100]`.
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
8. What's the sum of all the elements of the result?


1. and 2.

In [23]:
Innjoo_df = laptops_df[laptops_df['Brand']=='Innjoo'][['RAM', 'Storage', 'Screen']]
Innjoo_df

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

3.

In [26]:
X = Innjoo_df.values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

4.

In [38]:
X_transpose = X.T
XTX = X_transpose.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

5.

In [32]:
XTX_inv = np.linalg.inv(XTX)

print("Inverse of XTX:")
print(XTX_inv)

Inverse of XTX:
[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


6.

In [39]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

7.

In [40]:
w = XTX_inv.dot(X_transpose).dot(y)

print("w:")
print(w)

w:
[45.58076606  0.42783519 45.29127938]


8.

In [51]:
# Compute the sum of all elements in w
sum_w = np.sum(w)

print(f"Sum of all elements in w: {sum_w:.2f}")


Sum of all elements in w: 91.30
